#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PYTHON_BIN="${REPO_ROOT}/.venv/bin/python"

if [[ ! -x "${PYTHON_BIN}" ]]; then
  echo "Python virtualenv not found at ${PYTHON_BIN}" >&2
  exit 1
fi

export LOCAL_DFLASH_MODEL_PATH="${LOCAL_DFLASH_MODEL_PATH:-/Users/samuelfajreldines/dev/models/Qwen3.6-35B-A3B-4bit}"
export LOCAL_DFLASH_DRAFT_PATH="${LOCAL_DFLASH_DRAFT_PATH:-/Users/samuelfajreldines/dev/models/Qwen3.6-35B-A3B-DFlash}"
export LOCAL_DFLASH_MODEL_NAME="${LOCAL_DFLASH_MODEL_NAME:-qwen3.6-35b-a3b-dflash-local}"
export LOCAL_DFLASH_HOST="${LOCAL_DFLASH_HOST:-127.0.0.1}"
export LOCAL_DFLASH_PORT="${LOCAL_DFLASH_PORT:-8010}"
export LOCAL_DFLASH_BLOCK_SIZE="${LOCAL_DFLASH_BLOCK_SIZE:-10}"
export LOCAL_DFLASH_SLIDING_WINDOW_SIZE="${LOCAL_DFLASH_SLIDING_WINDOW_SIZE:-4096}"
export LOCAL_DFLASH_DISABLE_THINKING="${LOCAL_DFLASH_DISABLE_THINKING:-1}"
export LOCAL_DFLASH_MAX_TOKENS="${LOCAL_DFLASH_MAX_TOKENS:-32768}"
export LOCAL_DFLASH_CONTEXT_RESERVE="${LOCAL_DFLASH_CONTEXT_RESERVE:-256}"
export LOCAL_DFLASH_CONTEXT_WINDOW="${LOCAL_DFLASH_CONTEXT_WINDOW:-65536}"
export LOCAL_DFLASH_KEEP_ALIVE="${LOCAL_DFLASH_KEEP_ALIVE:--1}"
export LOCAL_DFLASH_STREAM_HEARTBEAT_SECONDS="${LOCAL_DFLASH_STREAM_HEARTBEAT_SECONDS:-2}"
export LOCAL_DFLASH_TURBOQUANT_BITS="${LOCAL_DFLASH_TURBOQUANT_BITS:-4}"
export LOCAL_DFLASH_MLX_MEMORY_LIMIT_GB="${LOCAL_DFLASH_MLX_MEMORY_LIMIT_GB:-}"
export LOCAL_DFLASH_MLX_CACHE_LIMIT_GB="${LOCAL_DFLASH_MLX_CACHE_LIMIT_GB:-}"
export LOCAL_DFLASH_NO_PRELOAD="${LOCAL_DFLASH_NO_PRELOAD:-0}"

cd "${REPO_ROOT}"
if command -v caffeinate >/dev/null 2>&1; then
  exec caffeinate -dimsu "${PYTHON_BIN}" "${REPO_ROOT}/scripts/local_api_server.py" "$@"
else
  exec "${PYTHON_BIN}" "${REPO_ROOT}/scripts/local_api_server.py" "$@"
fi
