#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PYTHON_BIN="${REPO_ROOT}/.venv/bin/python"

if [[ ! -x "${PYTHON_BIN}" ]]; then
  echo "Python virtualenv not found at ${PYTHON_BIN}" >&2
  exit 1
fi

export LOCAL_DFLASH_MODEL_PATH="${LOCAL_DFLASH_MODEL_PATH:-/Users/samuelfajreldines/dev/models/Qwen3.6-35B-A3B-4bit}"
export LOCAL_DFLASH_DRAFT_PATH="${LOCAL_DFLASH_DRAFT_PATH:-/Users/samuelfajreldines/dev/models/Qwen3.6-35B-A3B-DFlash}"
export LOCAL_DFLASH_MODEL_NAME="${LOCAL_DFLASH_MODEL_NAME:-qwen3.6-35b-a3b-dflash-local}"
export LOCAL_DFLASH_HOST="${LOCAL_DFLASH_HOST:-127.0.0.1}"
export LOCAL_DFLASH_PORT="${LOCAL_DFLASH_PORT:-8010}"
export LOCAL_DFLASH_BLOCK_SIZE="${LOCAL_DFLASH_BLOCK_SIZE:-10}"
export LOCAL_DFLASH_ADAPTIVE_BLOCK_SIZE="${LOCAL_DFLASH_ADAPTIVE_BLOCK_SIZE:-1}"
export LOCAL_DFLASH_ADAPTIVE_BLOCK_SIZE_MIN="${LOCAL_DFLASH_ADAPTIVE_BLOCK_SIZE_MIN:-8}"
export LOCAL_DFLASH_ADAPTIVE_BLOCK_SIZE_MAX="${LOCAL_DFLASH_ADAPTIVE_BLOCK_SIZE_MAX:-18}"
export LOCAL_DFLASH_ADAPTIVE_BLOCK_SIZE_GROW_THRESHOLD="${LOCAL_DFLASH_ADAPTIVE_BLOCK_SIZE_GROW_THRESHOLD:-0.95}"
export LOCAL_DFLASH_ADAPTIVE_BLOCK_SIZE_SHRINK_THRESHOLD="${LOCAL_DFLASH_ADAPTIVE_BLOCK_SIZE_SHRINK_THRESHOLD:-0.6}"
export LOCAL_DFLASH_SLIDING_WINDOW_SIZE="${LOCAL_DFLASH_SLIDING_WINDOW_SIZE:-4096}"
export LOCAL_DFLASH_DISABLE_THINKING="${LOCAL_DFLASH_DISABLE_THINKING:-1}"
export LOCAL_DFLASH_MAX_TOKENS="${LOCAL_DFLASH_MAX_TOKENS:-32768}"
export LOCAL_DFLASH_CONTEXT_RESERVE="${LOCAL_DFLASH_CONTEXT_RESERVE:-256}"
export LOCAL_DFLASH_CONTEXT_WINDOW="${LOCAL_DFLASH_CONTEXT_WINDOW:-65536}"
export LOCAL_DFLASH_KEEP_ALIVE="${LOCAL_DFLASH_KEEP_ALIVE:-300}"
export LOCAL_DFLASH_STREAM_HEARTBEAT_SECONDS="${LOCAL_DFLASH_STREAM_HEARTBEAT_SECONDS:-2}"
export LOCAL_DFLASH_TURBOQUANT_BITS="${LOCAL_DFLASH_TURBOQUANT_BITS:-4}"
export LOCAL_DFLASH_MLX_MEMORY_LIMIT_GB="${LOCAL_DFLASH_MLX_MEMORY_LIMIT_GB:-}"
export LOCAL_DFLASH_MLX_CACHE_LIMIT_GB="${LOCAL_DFLASH_MLX_CACHE_LIMIT_GB:-}"
export LOCAL_DFLASH_NO_PRELOAD="${LOCAL_DFLASH_NO_PRELOAD:-1}"
export LOCAL_DFLASH_RESPONSE_HISTORY_LIMIT="${LOCAL_DFLASH_RESPONSE_HISTORY_LIMIT:-1024}"
export LOCAL_DFLASH_PREFIX_CACHE_STATE_LIMIT="${LOCAL_DFLASH_PREFIX_CACHE_STATE_LIMIT:-2}"
export LOCAL_DFLASH_GLOBAL_PREFIX_CACHE_LIMIT="${LOCAL_DFLASH_GLOBAL_PREFIX_CACHE_LIMIT:-16}"

cd "${REPO_ROOT}"
if command -v caffeinate >/dev/null 2>&1; then
  exec caffeinate -dimsu "${PYTHON_BIN}" "${REPO_ROOT}/scripts/local_api_server.py" "$@"
else
  exec "${PYTHON_BIN}" "${REPO_ROOT}/scripts/local_api_server.py" "$@"
fi
